name: chat_realtime
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #svg
  flutter_svg: ^0.22.0

  #json serializable
  json_annotation: ^4.0.1
  json_serializable: ^4.1.0

  #socket
  socket_io_client: ^1.0.0

  #remote resources
  http: ^0.13.1

  #gstate manager
  flutter_bloc: ^7.0.0
  provider: ^5.0.0

  #helpers
  another_flushbar: ^1.10.17
  back_button_interceptor: ^5.0.0
  equatable: ^2.0.0
  dartz: ^0.10.0-nullsafety.1

  cupertino_icons: ^1.0.2

  #generators
  auto_route:
  injectable: ^1.3.0
  get_it: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator:
  injectable_generator:
  build_runner:
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/images/main/


